definitions:
  config:
    /hst:hst/hst:configurations/gogreen/hst:pages/productpage:
      jcr:primaryType: hst:component
      hst:referencecomponent: hst:abstractpages/twocolumns
      /main:
        jcr:primaryType: hst:component
        /left:
          jcr:primaryType: hst:component
          hst:template: productpage-main
          hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsContentComponent
